app:
  title: IDP Demo Portal
  baseUrl: http://localhost/backstage

organization:
  name: Platform Engineering

backend:
  baseUrl: http://localhost/backstage
  listen:
    port: 7007
  database:
    client: better-sqlite3
    connection: ':memory:'
  cors:
    origin: http://localhost/backstage
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]

auth:
  providers: {}

notifications:
  processors: {}
